### ISSUE TITLE
Feature: Terms and conditions, data policy

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#108]

**Comment by v-stamenova** [comment]
@TimKardol should we update priority?

**Comment by TimKardol** [comment]
Yes, should be added to the footer as two links. I think both policies are up to date or shouldn't change. Maybe check them for the years. I'll put this as high priority.

**Comment by TimKardol** [comment]
- Updated texts for the privacy policy and cookie consent
- Add banner for cookies that actually functions

**Comment by Lucky-Loek** [comment]
I wanted to create a bug report for this. This is actually legally required since you're storing PII so would be nice to add it...

**Comment by TimKardol** [comment]
@Lucky-Loek Yup, we are aware of it...

**Comment by TimKardol** [comment]
Closed in #587
