### ISSUE TITLE
UI/UX: Gradient background on companies, contact and FAQ page

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#114]
The following pages need a gradient background so it looks a bit more fun. 
- [x] Companies
- [x] Contact
- [x] FAQ
- [x] Speakers

**Comment by IGORnvk** [comment]
No speakers page? @TimKardol

**Comment by TimKardol** [comment]
> No speakers page? @TimKardol

I forgot that one. Yes the speakers page as well

**Comment by TimKardol** [comment]
Closed in #329
