### ISSUE TITLE
A one-man company can't register for a presentation

### ISSUE THREAD

**Issue by dwaard** [HZ-HBO-ICT/it-conference#153]
When I register myself as a company (rep?), but I'm the only person who will attend and represent the company, I can't request for a presentation.

### Steps to reproduce this behavior
1. Register as a company
2. Content mod approves the company
3. As company rep: search for a request for presentation

**Comment by v-stamenova** [comment]
Completed for #107 . After merge with development, will take care of it in the case of #149 as well. So not closed for now
