### ISSUE TITLE
Create a development environment

### ISSUE THREAD

**Issue by Ex6tenze** [HZ-HBO-ICT/it-conference#16]
- [x] Laravel Sail
- [x] SCSS loader (Vite, live reload)
- [x] Unit testing (PHPUnit, GitHub Workflows)
- [x] Wiki documentation
- [x] Tailwind
- [x] JetStream
- [x] [GitHub Project Workflows](https://github.com/orgs/HZ-HBO-ICT/projects/2/workflows/)
- [x] Mailpit

**Comment by TimKardol** [comment]
Can you add mailpit to the container?

**Comment by Ex6tenze** [comment]
> Can you add mailpit to the container?

I am adding it in the next commit :+1:

**Comment by Ex6tenze** [comment]
Instead of using sass, I chose to use the PostCSS pre-processor as it has native compatibility with the rest of the application. I have tested it, and it works perfectly fine with HMR.

**Comment by TimKardol** [comment]
Closing because this has already been merged!
