### ISSUE TITLE
Feature: As a contentmoderator I would like to see company and speaker details of approved companies

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#206]
Currently in the dashboard overview I see a list of Current companies / presentations etc. I would like to be able to click on the company in the list to be able to see the specific details. as well as of the speaker as so to be able to communicate with them or change things for them.

**Comment by TimKardol** [comment]
Partially fixed in #283 . You can view the details but not edit the details.
