### ISSUE TITLE
Feature As a contentmoderator when in my hub space to have a menu item link back to the moderator Dashboard

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#207]
It would be nice to have a link in my hub environment to go back to the content moderator Dashboard. Work around for now is log out and log on or have the specific url bookmarked.

**Comment by TimKardol** [comment]
This is going to be fixed in the content moderator dashboard rework. PR #133

**Comment by TimKardol** [comment]
Closed in #133
