### ISSUE TITLE
UI/UX: Add impression video from last year

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#208]
Add the impression video from last year to the website. Options
1)
- link to the youtube account video through the FAQ item on what is the conference explanation.
- https://www.youtube.com/@WeareInITTogether / channel 
- https://www.youtube.com/watch?v=k-Psaz0hdQI / video
-2) place on home page...
3) make a separate content page "Impression"  and embed the video

**Comment by TimKardol** [comment]
Closed in #226
