### ISSUE TITLE
Bug: Profile and logo image size in pixels are to large and in weird formats

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#209]
On the live environment the logo of the company is very much stretched everywhere. Will need some extra investigation.

**Comment by v-stamenova** [comment]
Maybe a potential fix is adding a rounded div around the image with size e.g. 56, and inside nestle a image with smaller size and remove the rounding

**Comment by TimKardol** [comment]
Think this is fixed in #281
