### ISSUE TITLE
Spelling: flash message uses incorrect tense

### ISSUE THREAD

**Issue by Lucky-Loek** [HZ-HBO-ICT/it-conference#227]
After signing up for a presentation, this flash message is shown. It should, however, use `sent` instead of `send`. Even better would be `We successfully received your request ...` since the user sends something.

![image](https://github.com/HZ-HBO-ICT/it-conference/assets/9716643/247f178f-e363-4a84-96ea-36f1ac6fb973)

**Comment by TimKardol** [comment]
Closed in #249
