### ISSUE TITLE
UI/UX: Add date of the conference on main page

### ISSUE THREAD

**Issue by Lucky-Loek** [HZ-HBO-ICT/it-conference#229]
There is now a countdown, but it never actually shows **when** the conference is... 😄 

![image](https://github.com/HZ-HBO-ICT/it-conference/assets/9716643/80d2dc35-aa26-4b65-96bc-ba3d745bb62c)

**Comment by TimKardol** [comment]
Fixed in development, will probably be updated on friday most likely.

**Comment by Lucky-Loek** [comment]
Sorry! I missed #200 in the closed option
