### ISSUE TITLE
Bug: Forgetting to fill in the number of requested participant as speakers clears the entire form upon saving

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#233]
Mike signed up as a speaker and stated this issie:
" I have just tried requesting to do a presentation. I submitted and just got the blank screen like I hadn't done anything. Note: the only thing I didn't do was select a preferred number of max participants. Perhaps that caused an issue? Anyway, I have just re-submitted - chosen 400 as max preferred - and it works "

Fix could be to make the preferred participants visibly mandatory? or not ;-)

![MicrosoftTeams-image (11)](https://github.com/HZ-HBO-ICT/it-conference/assets/60391673/3cf6151d-d0fb-4641-b6b1-13ad2b28c360)

**Comment by v-stamenova** [comment]
Fixed in #241
