### ISSUE TITLE
Feature: Content moderator should be able to insert a booth for sponsors

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#282]
Not sure if this is tackeld somewhere else or a new feature. But Your Surprise for instance has a booth within it's gold package however I am not able to add it for them. Same for for instance the silver and brons packages.. I can now only see the companies applying for a booth which makes it an incomplete list of booth owners.

**Comment by TimKardol** [comment]
Closed in #283
