### ISSUE TITLE
As a moderator I cannot see for what sponsorhip the company signed up for anymore

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#299]
Just saw that intermax applied for sponsorship but I have no idea which one... So don't know what exactly I am approving to now.. Used to be able to see that so somewhere in the reengineering something was left out? I'll leave the approval for now untill I know what they selected. can you tell from the admin side somehow?

**Comment by TimKardol** [comment]
Closed in #300
