### ISSUE TITLE
Enhancement: Ordering speakers according to sponsorship is not accurate on the website speakers page

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#307]
Marijn van wijngaarden for example is a speaker from a Bronze sponsor but not mentioned before Daan on the speakers page. So this list is not accurate as of yet. Your Surprise will come with gold sponsors so again speakers should be mentioned in following order of sponsorship and then everyone else.

**Comment by TimKardol** [comment]
Closed in #313
