### ISSUE TITLE
Feature: Place the Keynotespeaker under the attention of the website visitor

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#319]
This enhacement is twofold. 
1. We need the keynote into the program I just do not know if we need to put it as a fixed element of every participants programme (or have people select it...
2. We need to add it ourselves since this is a VIP speaker...
3. On the homepage of the website at the speakers section we need to highlight Jolanda... before the 27th final programme

**Comment by v-stamenova** [comment]
@TimKardol will tackle this immediately after the CRUDs

**Comment by TimKardol** [comment]
Closed in #349
