### ISSUE TITLE
Bug: In mobile version only Gold Sponsor is visible on the landing page

### ISSUE THREAD

**Issue by v-stamenova** [HZ-HBO-ICT/it-conference#323]

**Comment by IGORnvk** [comment]
Well, It was actually done on purpose due to lack of space on small screens, but I can try to look for other solutions.

**Comment by TimKardol** [comment]
@IGORnvk Can just be a simple stack from top to bottom. Keep it simple if you are going to work on it.

**Comment by IGORnvk** [comment]
> @IGORnvk Can just be a simple stack from top to bottom. Keep it simple if you are going to work on it.

Okay!

**Comment by TimKardol** [comment]
Closed in #331
