### ISSUE TITLE
Feature: Content moderator can set deadlines

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#325]
Content moderator should be able to set deadlines for company registrations and presentation requests. Maybe even other deadlines.

**Comment by IGORnvk** [comment]
> I have some general dates here that you might need. 7 september: Start of company registration 4 or 7 october: Start of participant registration

So there should be a start date as well? Not only the end date/deadline? Also, does the start of participant registration means the end of company registration?
