### ISSUE TITLE
Caroline ten hove as owner of Maxxton will need to be replaced with Ramonvan Loon

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#330]
Caroline has changed companies and does not work for Maxxton any longer, could her name as owner be changed into Ramon van Loon ?

**Comment by TimKardol** [comment]
Yes, but they need to do it themselves. They can edit the profile when logging. I see they used their info@maxxton.nl account. If they don't have the password they can reset it and then login. When they have logged in again, they can click on 'Edit Profile' in their dashboard and change their full name.

**Comment by TimKardol** [comment]
But they have access to the email account info@... right? So they can change the company rep's name themselves if they login? This is not something we should do. If Ramon follows the steps I mentioned the issue is fixed.
