### ISSUE TITLE
All participants of a company are showing up as speaker

### ISSUE THREAD

**Issue by eliotolhoek** [HZ-HBO-ICT/it-conference#338]
One of the companies just reported an issue:

_Geachte heer/mevrouw,

Volgens mij gaat er iets fout op de website, pagina sprekers. Mijn presentatie staat opeens 3 keer in de lijst maar met verschillende sprekers (alle teamleden die zijn aangemeld).

Met vriendelijke groet / Kind regards,

Wilko van de Velde_

**Comment by TimKardol** [comment]
Closed in #340
