### ISSUE TITLE
Feature: The opening slot cannot be edited for additional description

### ISSUE THREAD

**Issue by daphneheertjes** [HZ-HBO-ICT/it-conference#339]
We tried together with Valeria to place additional information about the Keynote into the opening timeslot but then an error occured. However a Keynote is the most important part of a conference and usually the one talk you attract participants with (in real life anyway) Since we booked an VIP speaker could we somehow get some info about her ?

a backup now could be the by Tim mentioned hard coded part on the Home page about the Keynote speaker and Bio, Don't know when the next release was planned and what should be in it but might be something to consider. I prefer that one, but don't know how soon that is shown on the website

A future feature should be adding enough of a description to the opening schedule part and make it editable

**Comment by v-stamenova** [comment]
Closed in #462
