### ISSUE TITLE
Bug: black color of text in dark mode on a presentation page

### ISSUE THREAD

**Issue by IGORnvk** [HZ-HBO-ICT/it-conference#344]
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/71547534/550cd614-e9b1-4a9e-aafd-66e75457a1e5)
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/71547534/dc1bcc72-e306-4586-94d6-4bc58e9c72ea)

**Comment by TimKardol** [comment]
Closed in #343
