### ISSUE TITLE
Security: Password Policy

### ISSUE THREAD

**Issue by kaankoylu** [HZ-HBO-ICT/it-conference#352]
To improve account security, We can add a requirement for at least one special character to the current password policy.

**Comment by Lucky-Loek** [comment]
The only password policy that's proven to be safe is a minimum amount of character: at least 12 and preferably 16. Enforcing other, arbirtrary rules leads to people creating bad passwords and worse: reusing them.

https://pages.nist.gov/800-63-3/sp800-63b.html#appA

**Comment by TimKardol** [comment]
I agree with @Lucky-Loek on this one. The better plan is to up the minimum amount of characters.

**Comment by TimKardol** [comment]
Closed in #403
