### ISSUE TITLE
Bug: Countdown/date not visible on welcome page

### ISSUE THREAD

**Issue by v-stamenova** [HZ-HBO-ICT/it-conference#354]

**Comment by IGORnvk** [comment]
Is it still relevant since we are redoing the entire welcome page? @v-stamenova

**Comment by v-stamenova** [comment]
I think so, but I think @popo0015 should be dealing with that considering the fact she's redoing the main page

**Comment by TimKardol** [comment]
Yes, this issue will be linked to that pull request when Silvia gets to it.

**Comment by IGORnvk** [comment]
I mean... I made the date not visible on the mobile sized devices last time, because it didn't fit

**Comment by TimKardol** [comment]
Closed in #401
