### ISSUE TITLE
Frontend/Backend/Rework: FAQ page

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#379]
Currently the FAQ is hardcoded and probably due for a redesign in the UI department as well. I think it would be very nice if the Content Moderators are able to create the FAQ from their dashboard. 

**Suggestions:**
- New questions can be added by Moderators
- Questions need a new UI layout
- Questions & Answers can be edited by Moderators

**Comment by v-stamenova** [comment]
Resolved in #532
