### ISSUE TITLE
Feature: Assign roles as Content Moderator

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#392]
> As a Event organizer I can assign roles to new conference team members
> - I can assign, edit, delete a role to a system user 
> - I can add edit or read access for different parts in the system to a system user 

Part of this feature can also be added to the company representative. They will be limited to only changing user roles within the company.

Second point in the quote means that policies are able to be edited from the frontend. I would, for now, advise against this. At least until we have a strong policy manager that we understand.

**Comment by v-stamenova** [comment]
Resolved in #533
