### ISSUE TITLE
Feature: Participants and Companies must be able to request presentations

### ISSUE THREAD

**Issue by v-stamenova** [HZ-HBO-ICT/it-conference#397]
The current edition doesn't allow to request presentations yet. There are a lot edge cases to this but the basic business logic goes as:
- A participant can request only one presentation

- A company can request only one presentation __UNLESS__
    - The company is a gold sponsor - they have 2 presentations
    - The company is HZ - they have unlimited presentations 

- A speaker can have only one presentation

**Comment by TimKardol** [comment]
Closed in #399
