### ISSUE TITLE
Bug: Countdown on the welcome page

### ISSUE THREAD

**Issue by IGORnvk** [HZ-HBO-ICT/it-conference#413]
**Describe the bug**
When switching to any other page through nav bar and then returning to the welcome page, the countdown doesn't appear.

**To Reproduce**
1. Go to welcome page
2. Click on any other page on the navbar (e.g. speakers)
3. Get back to welcome page
4. There is no countdown now!

**Expected behavior**
The countdown should be there every time I access the welcome page.

**Screenshots**
Before:
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/71547534/4c380d9b-05c2-4192-9d09-84f2142757c3)

After you navigate to any other page and go back:
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/71547534/ee5986b8-753f-4816-b094-76962b62995c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**
On mobile version it behaves the same

**Comment by TimKardol** [comment]
Closed in #443
