### ISSUE TITLE
Bug: Register buttons when authenticated

### ISSUE THREAD

**Issue by IGORnvk** [HZ-HBO-ICT/it-conference#415]
**Describe the bug**
Register buttons are displayed even though the user is already authenticated.

**To Reproduce**
1. Login/Register
2. Go to welcome page
3. See that 'register as participant/company' buttons are still there

**Expected behavior**
These buttons shouldn't be there when authenticated

**Screenshots**
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/71547534/321e74d6-5b57-44aa-9a46-e3fae204902f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**
exists on mobile version as well

**Comment by TimKardol** [comment]
Closed in #419
