### ISSUE TITLE
Bug/Question: Footer in authorised pages

### ISSUE THREAD

**Issue by v-stamenova** [HZ-HBO-ICT/it-conference#417]
With the update of the welcome page now we have a new footer. Is it necessary to have the big footer throughout all pages including the crew ones? Can we create a smaller one for those authorised pages or do we rely on the fact that we'll fix the scrolling and won't be covering so much of the screen?

<img width="954" alt="image" src="https://github.com/HZ-HBO-ICT/it-conference/assets/77020646/5176ac0b-6dd4-427c-af00-05cdaf99c4cf">

**Comment by popo0015** [comment]
I am currently working on the dashboards. The idea is that the footer is not present in the dashboard itself, so I guess it won't be an issue.

**Comment by TimKardol** [comment]
Closing this as it will not be in the authorised pages.
