### ISSUE TITLE
Bug: house number input doubled

### ISSUE THREAD

**Issue by dwaard** [HZ-HBO-ICT/it-conference#420]
**Describe the bug**
On the `/moderator/companies/create` page, the input "house number" appears twice

**To Reproduce**
1. Go to 'Admin' -> 'Companies'
2. Click on 'Invite a company'
3. Scroll down to 3rd and 5th form input
4. See error "House number" appear twice

**Expected behavior**
First input should be removed

**Screenshots**
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/6419619/fed947d2-17dc-4046-ba0f-b9a6ad409880)

**Desktop (please complete the following information):**
 - any
 - 
**Smartphone (please complete the following information):**
 - any
  
**Additional context**
Not applicable

**Comment by v-stamenova** [comment]
It seems like it has been fixed in development at some point, unsure when.

<img width="532" alt="image" src="https://github.com/HZ-HBO-ICT/it-conference/assets/77020646/b52f780c-a2ad-445b-96e5-fab8f38830ed">
