### ISSUE TITLE
Bug: Dark mode styling errors

### ISSUE THREAD

**Issue by dwaard** [HZ-HBO-ICT/it-conference#422]
**Describe the bug**
In dark mode, the following styling issues occur:

- /user/profile: "Receive notifications and reminders on email" in dark font
- /crew/sponsorships/{id} : "When deleted the company will no longer appear as a sponsor. However, the company representative is allowed to apply for another sponsorship" in dark font
- /moderator/presentations/{id}: Presentation information and Participants
- /moderator/rooms/{id}: Room information

**To Reproduce**
1. Go to each page in the list
2. Click on 'dark mode toggle button'
3. See error

**Expected behavior**
Font color should be consistent

**Screenshots**
Example:
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/6419619/82510059-e208-437f-be55-17d5662f1365)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by TimKardol** [comment]
Fixed in #438
