### ISSUE TITLE
Feature request: WYSIWYG (markdown) editor for comany and presentation details

### ISSUE THREAD

**Issue by dwaard** [HZ-HBO-ICT/it-conference#429]
We need rich text for description fields like company details.
 
Suggestion:

- Find a (JavaScript) rich text editor that supports markdown (like the one used in GitHub?)
- Create a Blade and/or Livewire component that can 'replace' current `<textarea>`s.

Use this component just like a textarea:
```html
<x-rich-textarea id="description" wire:model="form.description"
                              class="..."
                              name="description" required
                    ></x-rich-textarea>
```

**Comment by v-stamenova** [comment]
It seems like we'd have to make some sort of trade-off if we decide to use one. For now the viable options seem to be:
- SimpleMDN
- Milkdown
- WYSIMARK

All of them are JS editor which makes styling a pain. SimpleMDN is rather outdated (there haven't been any activity over 8 years there); Milkdown is actively in development (but the plugins are not matching our needs exactly e.g. the menu) and WYSIMARK again is hard to customize.

**Comment by v-stamenova** [comment]
PR #532 introduces a markdown editor that is a component so can be used in 2025.

**Comment by v-stamenova** [comment]
Dup #142
