### ISSUE TITLE
Emails should be send from the info@weareinittogether.nl email address

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#43]
Currently when clicking to create an email, outlook gets opened with a new message. However as the content moderators cannot add the mailbox to their outlook currently, it should automatically open the webversion.

Task is to find a way to make this work somehow.

**Comment by v-stamenova** [comment]
I think this one should go either low priority or after refactoring. In order for the webversion to be open (from what I read) the content moderators need to set outlook on the web as the default email client and configure their browsers.

**Comment by TimKardol** [comment]
Whats the status on this?

**Comment by v-stamenova** [comment]
@TimKardol should be closed right?
