### ISSUE TITLE
Bug: Company member invitation needs to resend email verification link

### ISSUE THREAD

**Issue by dwaard** [HZ-HBO-ICT/it-conference#430]
**Describe the bug**
When a company member is invited, the invited user is sent an email with a link. After following the link, the user can fill out his user details and then a page appears showing that the user needs to verify his email (again). The email isn't sent, so the user needs to click the button to resend the mail.

**To Reproduce**
1. One user creates a company
2. He invites another user
3. Other user checks the mail
4. Fills out registration form
5. See error

**Expected behavior**
The process should be:
1. company rep invites user
2. User checks mail and opens the invitation link
3. The email address is set to verified and the registration for is shown
4. User fills out registration form
5. User is logged in

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by TimKardol** [comment]
Closed in #440
