### ISSUE TITLE
Rework: company roles logic

### ISSUE THREAD

**Issue by dwaard** [HZ-HBO-ICT/it-conference#431]
Currently, the companyrep needs to select a role when inviting company members. When a member is a speaker, he can request for a presentation. When a booth is approved, the companyrep can invite a member as a booth owner. Once done, the companyrep cannot manage the booth ownership.

I suggest the following for booth ownership:
- Companyrep can invite and remove members
- When creating a booth registration, he selects one of the members (including himself) as booth owner
- After approval, he can update the booth ownership
- When he deletes the boothowner the ownership is automatically set to the companyrep

And for the presentations:
- Any user can request for a presentation
- When the user has role 'company member', the company is associated with the presentation (optional: the user can select whether or not the presentation should be attached to the company)
- Companyrep can see all the presentations that are associated with the company
- Whe the companyrep removes the member that has a presentation, the presentation will be detached from the company

**Comment by dwaard** [comment]
Btw, in PR #411 , the 'speaker' and 'booth owner' roles are removed, so inviting company members lead to errors

**Comment by TimKardol** [comment]
Closed in #440
