### ISSUE TITLE
Frontend: Portal heading change to important links

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#467]
Don't really understand what is meant with this. @IGORnvk Maybe you overheard something?

**Comment by IGORnvk** [comment]
![image](https://github.com/HZ-HBO-ICT/it-conference/assets/71547534/892ce4c4-8ee2-4550-92f6-140c0659682a)
I guess the word "Portal" has to be changed to "Important links" @TimKardol
