### ISSUE TITLE
Bug: Links in footer are not linking

### ISSUE THREAD

**Issue by TimKardol** [HZ-HBO-ICT/it-conference#473]
- Links to legal, privacy etc at the bottom of the pages needs to be linked to an actual page with information.

**Comment by TimKardol** [comment]
Partially closed in #513

**Comment by TimKardol** [comment]
Reopened because some things still need to be done:

- [ ] Privacy Policy
- [ ] Terms & Conditions
- [ ] Last check for other links

**Comment by v-stamenova** [comment]
> Reopened because some things still need to be done:
> 
> * [ ]  Privacy Policy ([Feature: Terms and conditions, data policy #108](https://github.com/HZ-HBO-ICT/it-conference/issues/108) [Feature: Cookie banner #109](https://github.com/HZ-HBO-ICT/it-conference/issues/109))
> * [ ]  Terms & Conditions ([Feature: Terms and conditions, data policy #108](https://github.com/HZ-HBO-ICT/it-conference/issues/108) [Feature: Cookie banner #109](https://github.com/HZ-HBO-ICT/it-conference/issues/109))
> * [ ]  Last check for other links

@TimKardol any chance you can sit with Daphne or to create them yourself?

**Comment by TimKardol** [comment]
Closed in #587
